### ISSUE TITLE
Game refuses to load with mod installed

### ISSUE THREAD

**Issue by Carnaxus** [bdew-minecraft/factorium#1]
I'm running 1.19 with Forge 41.0.110; whenever I enabled bdlib and Factorium, my game refuses to launch, stating that bdlib and Factorium "failed to initialize."  I've got Bdlib 1.20.0.3 and Factorium 1.2.0.2; I can upload the log if needed.

Other mods:
Advanced Chimneys 9.1.3.0
Catalogue 1.6.3
Craftable Horse Armor and Saddle 1.9
Configured 1.5.5
Elevator Mod 1.8.6
ForgeEndertech 10.0.3.0
Journeymap 5.8.5rc5
JEI 11.1.0.233
Macaw's Bridges2.0.3
ScalableCatsForce 2.13.8 build 6

(Copied/pasted from my comment on Curseforge)

**Comment by bdew** [comment]
You need newer versions for forge newer than 41.0.64

[Factorium 1.2.0.5](https://www.curseforge.com/minecraft/mc-mods/factorium/files/3875576) and [BDLib 1.22.0.5](https://www.curseforge.com/minecraft/mc-mods/bdlib/files/3875569) are the current latest versions.

Lots of breaking changes around that forge version so will likely need to update other mods too
